version: "3.7"
services:
  db:
    container_name: user-postgre
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: userdatabase
    ports:
      - "5433:5433"
  pgadmin:
    container_name: user-pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5051:80"
  app:
    container_name: dockerizeapp
    build: .
    ports:
      - "5005:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/userdatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db